# Generated by Django 4.1.5 on 2023-01-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencypair',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='currencypair',
            unique_together={('curr_code', 'language', 'target_code')},
        ),
    ]
