# Generated by Django 4.1.5 on 2023-01-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_alter_currencypair_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencypair',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
